/**
 * 二十种公开卡牌数据。art/icon 等字段只用于展示；规则只读取显式规则字段。
 * 三类牌为 basic / tactic / equipment，响应时机由 usageMode 与 responseTypes 描述。
 */
const card = (definition) => Object.freeze({
  usageMode: "active", responseTypes: [], counterable: definition.category === "tactic",
  counterScope: "card", ignoresDistance: false, selectionFlow: [], ...definition
});

export const CARD_DEFINITIONS = Object.freeze({
  assault: card({ definitionId:"assault", name:"突袭", category:"basic", categoryName:"基础牌", targetType:"singleEnemyInRange", subtypes:["attack","assault"], description:"对攻击距离1内的一名敌人造成1点可格挡伤害。", count:30, aiValue:4, art:"./assets/cards/assault.svg", icon:"./assets/cards/assault.svg", accent:"#b84a2f", frameStyle:"strike", flavorText:"刀光先于战意抵达。" }),
  recover: card({ definitionId:"recover", name:"调息", category:"basic", categoryName:"基础牌", usageMode:"both", responseTypes:["dyingRescue"], targetType:"self", subtypes:["heal","rescue"], description:"出牌阶段令自己恢复1点生命；濒死时可救援自己或队友。", count:10, aiValue:6, art:"./assets/cards/recover.svg", icon:"./assets/cards/recover.svg", accent:"#4f8468", frameStyle:"vital", flavorText:"一息尚存，灵脉不绝。" }),
  block: card({ definitionId:"block", name:"格挡", category:"basic", categoryName:"基础牌", usageMode:"response", responseTypes:["block"], targetType:"responseOnly", subtypes:["defense","response"], description:"响应突袭；弃置要求数量的格挡，令该次攻击无效。", count:25, aiValue:6, art:"./assets/cards/block.svg", icon:"./assets/cards/block.svg", accent:"#54728a", frameStyle:"guard", flavorText:"山岳不语，自有回响。" }),
  charge: card({ definitionId:"charge", name:"聚能", category:"basic", categoryName:"基础牌", targetType:"self", subtypes:["energy"], description:"获得1点能量，不能超过上限。", count:10, aiValue:4, art:"./assets/cards/charge.svg", icon:"./assets/cards/charge.svg", accent:"#b4872f", frameStyle:"core", flavorText:"星火归心，静待雷鸣。" }),

  scout: card({ definitionId:"scout", name:"窥探", category:"tactic", categoryName:"战术牌", targetType:"otherWithCards", subtypes:["information","hidden-selection"], description:"查看一名其他角色至多2张指定手牌；信息只对你公开。", count:4, aiValue:5, ignoresDistance:true, selectionFlow:["target","hiddenCards:upTo2"], art:"./assets/cards/scout.svg", icon:"./assets/cards/scout.svg", accent:"#4b718b", frameStyle:"oracle", flavorText:"潮声掩住了情报的脚步。" }),
  transfer: card({ definitionId:"transfer", name:"转移", category:"tactic", categoryName:"战术牌", targetType:"multiStage", subtypes:["control","hidden-selection"], description:"选择一名有手牌的来源、一名不同的接收者，再转移1张指定手牌。", count:4, aiValue:5, ignoresDistance:true, selectionFlow:["source","receiver","hiddenCard:1"], art:"./assets/cards/transfer.svg", icon:"./assets/cards/transfer.svg", accent:"#3f6099", frameStyle:"current", flavorText:"物随势转，去处不由旧主。" }),
  exposeWeakness: card({ definitionId:"exposeWeakness", name:"破势", category:"tactic", categoryName:"战术牌", targetType:"self", subtypes:["status","attack-buff"], description:"获得1层破势；下次主动突袭伤害增加全部层数并消耗。", count:4, aiValue:6, art:"./assets/cards/expose-weakness.svg", icon:"./assets/cards/expose-weakness.svg", accent:"#8d332f", frameStyle:"fracture", flavorText:"先断其势，再断其锋。" }),
  shockwave: card({ definitionId:"shockwave", name:"震荡", category:"tactic", categoryName:"战术牌", targetType:"allEnemies", subtypes:["attack","assault","area"], description:"按座位顺序分别对所有敌人进行1次突袭；无视距离和突袭次数。目标反制时只取消对自己的效果。", count:2, aiValue:8, counterScope:"target", ignoresDistance:true, art:"./assets/cards/shockwave.svg", icon:"./assets/cards/shockwave.svg", accent:"#c35a35", frameStyle:"impact", flavorText:"大地替怒火发声。" }),
  provoke: card({ definitionId:"provoke", name:"挑衅", category:"tactic", categoryName:"战术牌", targetType:"allEnemies", subtypes:["coercion","hp-loss"], description:"每名敌人弃置1张突袭，否则失去1点生命。", count:4, aiValue:7, ignoresDistance:true, art:"./assets/cards/provoke.svg", icon:"./assets/cards/provoke.svg", accent:"#a44935", frameStyle:"impact", flavorText:"怒意一旦应声，代价便已写下。" }),
  plunder: card({ definitionId:"plunder", name:"掠夺", category:"tactic", categoryName:"战术牌", targetType:"otherWithCards", subtypes:["control","hidden-selection"], description:"获得一名其他角色的1张指定手牌；牌名不公开。", count:2, aiValue:7, ignoresDistance:true, selectionFlow:["target","hiddenCard:1"], art:"./assets/cards/plunder.svg", icon:"./assets/cards/plunder.svg", accent:"#714985", frameStyle:"chain", flavorText:"秘密总有第二位主人。" }),
  destroy: card({ definitionId:"destroy", name:"破坏", category:"tactic", categoryName:"战术牌", targetType:"otherWithCards", subtypes:["control","hidden-selection"], description:"弃置一名其他角色的1张指定手牌，并公开其牌名。", count:4, aiValue:6, ignoresDistance:true, selectionFlow:["target","hiddenCard:1"], art:"./assets/cards/destroy.svg", icon:"./assets/cards/destroy.svg", accent:"#7a3f36", frameStyle:"fracture", flavorText:"断裂之声让秘密无处藏身。" }),
  counter: card({ definitionId:"counter", name:"反制", category:"tactic", categoryName:"战术牌", usageMode:"response", responseTypes:["counter"], targetType:"responseOnly", subtypes:["response","counter"], description:"响应一张战术牌并取消其效果；面对群伤牌时只取消对自己的效果。反制本身也可以被其他反制响应。", count:4, aiValue:8, counterable:true, art:"./assets/cards/counter.svg", icon:"./assets/cards/counter.svg", accent:"#59406e", frameStyle:"seal", flavorText:"印成，则万法暂寂。" }),
  harvest: card({ definitionId:"harvest", name:"收获", category:"tactic", categoryName:"战术牌", targetType:"none", subtypes:["draw"], description:"摸2张牌。", count:4, aiValue:7, art:"./assets/cards/harvest.svg", icon:"./assets/cards/harvest.svg", accent:"#71834b", frameStyle:"vital", flavorText:"耐心让每一粒星火结实。" }),
  duel: card({ definitionId:"duel", name:"决斗", category:"tactic", categoryName:"战术牌", targetType:"singleEnemy", subtypes:["duel","attack-discard"], description:"目标先开始，双方轮流弃置突袭；首先不能或放弃者受到1点伤害。", count:4, aiValue:7, ignoresDistance:true, art:"./assets/cards/duel.svg", icon:"./assets/cards/duel.svg", accent:"#933d31", frameStyle:"strike", flavorText:"胜负只隔着下一次出刃。" }),
  mutualBenefit: card({ definitionId:"mutualBenefit", name:"互利", category:"tactic", categoryName:"战术牌", targetType:"none", subtypes:["public-pool","draw"], description:"展示等同存活人数的牌，从你开始按座位顺序每人选择1张。", count:3, aiValue:7, ignoresDistance:true, selectionFlow:["publicPool"], art:"./assets/cards/mutual-benefit.svg", icon:"./assets/cards/mutual-benefit.svg", accent:"#5a8b7f", frameStyle:"ward", flavorText:"同桌之上，各取所需。" }),
  symbiosis: card({ definitionId:"symbiosis", name:"共生", category:"tactic", categoryName:"战术牌", targetType:"allLiving", subtypes:["heal","global"], description:"按座位顺序令所有存活角色各恢复1点生命。", count:1, aiValue:8, ignoresDistance:true, art:"./assets/cards/symbiosis.svg", icon:"./assets/cards/symbiosis.svg", accent:"#45856b", frameStyle:"vital", flavorText:"万脉同息，枯处亦生。" }),

  energyDevice: card({ definitionId:"energyDevice", name:"充能装置", category:"equipment", categoryName:"装备牌", targetType:"self", subtypes:["equipment","energy"], description:"回合开始获得能量时额外获得1点。", count:2, aiValue:7, counterable:false, art:"./assets/cards/energy-device.svg", icon:"./assets/cards/energy-device.svg", accent:"#b4872f", frameStyle:"machine", flavorText:"微光沿铜轨汇入核心。" }),
  recycleDevice: card({ definitionId:"recycleDevice", name:"回收装置", category:"equipment", categoryName:"装备牌", targetType:"self", subtypes:["equipment","draw"], description:"自己回合首次主动使用战术牌后摸1张，即使该牌被反制。", count:2, aiValue:8, counterable:false, art:"./assets/cards/recycle-device.svg", icon:"./assets/cards/recycle-device.svg", accent:"#7d8260", frameStyle:"machine", flavorText:"废弃的余响仍可再次运转。" }),
  defenseDevice: card({ definitionId:"defenseDevice", name:"防御装置", category:"equipment", categoryName:"装备牌", targetType:"self", subtypes:["equipment","judgment","defense"], description:"遭受普通或震荡突袭前判定：战术免疫；基础获得并继续；装备失去1生命并终止攻击。", count:2, aiValue:9, counterable:false, art:"./assets/cards/defense-device.svg", icon:"./assets/cards/defense-device.svg", accent:"#58788c", frameStyle:"machine", flavorText:"齿轮先一步听见危险。" }),
  battleDevice: card({ definitionId:"battleDevice", name:"战斗装置", category:"equipment", categoryName:"装备牌", targetType:"self", subtypes:["equipment","attack"], description:"你的普通与震荡突袭需要目标同时弃置2张格挡才能防御。", count:2, aiValue:9, counterable:false, art:"./assets/cards/battle-device.svg", icon:"./assets/cards/battle-device.svg", accent:"#9a6139", frameStyle:"machine", flavorText:"双重压力让防线发出哀鸣。" })
});

export const CARD_COUNTS = Object.freeze(Object.fromEntries(Object.values(CARD_DEFINITIONS).map((definition) => [definition.definitionId, definition.count])));
export const TOTAL_CARD_COUNT = Object.values(CARD_COUNTS).reduce((sum, count) => sum + count, 0);
