/*
模块职责
唯一拥有 FiveRealms 二十七种卡牌的纯静态领域定义；不含 AI 价值、UI 素材、展示样式或运行时 resolver。

上游
Domain card rules、Application action、AI 与 presentation consumers。

下游
无。

状态边界
纯静态事实，不读取或写入运行时状态。

信息边界
全部字段均为公开卡牌规则事实，无隐藏信息。

架构约束
不得依赖 application/adapters/ui/audio/ai/Game 或任何 runtime 模块；牌堆数量/deck composition 由 RulesetDefinition 唯一拥有。
*/

export const CARD_DEFINITIONS = Object.freeze({
  assault: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "assault",
    name: "突袭",
    category: "basic",
    targetType: "singleEnemyInRange",
    subtypes: Object.freeze(["attack", "assault"]),
    description: "对攻击距离1内的一名敌人造成1点可格挡伤害。",
    baseDamage: 1,
  }),

  recover: Object.freeze({
    usageMode: "both",
    responseTypes: Object.freeze(["dyingRescue"]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "recover",
    name: "调息",
    category: "basic",
    targetType: "self",
    subtypes: Object.freeze(["heal", "rescue"]),
    description: "出牌阶段令自己恢复1点生命；濒死时可使用「调息」救援自己或队友。",
    healAmount: 1,
  }),

  block: Object.freeze({
    usageMode: "response",
    responseTypes: Object.freeze(["block"]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "block",
    name: "格挡",
    category: "basic",
    targetType: "responseOnly",
    subtypes: Object.freeze(["defense", "response"]),
    description: "使用要求数量的「格挡」，令该次攻击无效。",
  }),

  charge: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "charge",
    name: "聚能",
    category: "basic",
    targetType: "self",
    subtypes: Object.freeze(["energy"]),
    description: "获得1点能量。",
    energyGain: 1,
  }),

  shield: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "shield",
    name: "护盾",
    category: "basic",
    targetType: "singleAlly",
    subtypes: Object.freeze(["defense", "shield", "support"]),
    description: "令自己或一名存活队友获得1点护盾；每点护盾免疫1点伤害。",
    shieldAmount: 1,
  }),

  scout: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: true,
    selectionFlow: Object.freeze(["target", "hiddenCards:upTo2"]),
    definitionId: "scout",
    name: "窥探",
    category: "tactic",
    targetType: "otherWithCards",
    subtypes: Object.freeze(["information", "hidden-selection"]),
    description: "查看一名其他角色至多2张指定手牌。",
    maxRevealCount: 2,
  }),

  transfer: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze(["source", "receiver", "handCard:1"]),
    definitionId: "transfer",
    name: "转移",
    category: "tactic",
    targetType: "multiStage",
    subtypes: Object.freeze(["control", "hidden-selection"]),
    description: "选择距离1内一名拥有手牌的来源和一名不同接收者，将其中1张手牌转移至接收者手牌；不能转移装备区的牌。",
    effectRange: 1,
    targetZones: Object.freeze(["hand"])
  }),

  exposeWeakness: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "exposeWeakness",
    name: "破势",
    category: "tactic",
    targetType: "self",
    subtypes: Object.freeze(["status", "attack-buff"]),
    description: "获得1层「破势」；「破势」可以使「突袭」伤害额外增加相应层数；层数可叠加，打出「突袭」后消耗所有层数。",
    stacksGain: 1,
  }),

  shockwave: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "target",
    ignoresDistance: true,
    selectionFlow: Object.freeze([]),
    definitionId: "shockwave",
    name: "震荡",
    category: "tactic",
    targetType: "allEnemies",
    subtypes: Object.freeze(["attack", "assault", "area"]),
    description: "对所有敌人进行1次「突袭」；目标使用「反制」时只取消对自己的效果。",
    perTargetDamage: 1,
  }),

  provoke: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "target",
    ignoresDistance: true,
    selectionFlow: Object.freeze([]),
    definitionId: "provoke",
    name: "挑衅",
    category: "tactic",
    targetType: "allEnemies",
    subtypes: Object.freeze(["coercion", "damage"]),
    description: "每名敌人打出1张「突袭」，否则受到1点伤害。",
    failDamage: 1,
  }),

  leverage: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze(["firstTarget", "equipment", "secondTarget", "confirm"]),
    definitionId: "leverage",
    name: "借势",
    category: "tactic",
    targetType: "multiStage",
    subtypes: Object.freeze(["coercion", "assault", "equipment-control"]),
    description: "选择一名有装备且攻击范围内存在其他角色的其他角色，再选择其攻击范围内的一名其他角色。前者可对后者使用1张「突袭」；若拒绝，你获得其指定装备。",
  }),

  plunder: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze(["target", "zoneCard:1"]),
    definitionId: "plunder",
    name: "掠夺",
    category: "tactic",
    targetType: "otherWithCardsOrEquipment",
    subtypes: Object.freeze(["control", "hidden-selection", "equipment-control"]),
    description: "获得距离2内一名其他角色的1张指定手牌或装备牌。",
    effectRange: 2,
    targetZones: Object.freeze(["hand", "equipment"])
  }),

  destroy: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: true,
    selectionFlow: Object.freeze(["target", "zoneCard:1"]),
    definitionId: "destroy",
    name: "破坏",
    category: "tactic",
    targetType: "otherWithCardsOrEquipment",
    subtypes: Object.freeze(["control", "hidden-selection", "equipment-control"]),
    description: "弃置一名其他角色的1张指定手牌或装备牌，并公开其牌名。",
    targetZones: Object.freeze(["hand", "equipment"])
  }),

  counter: Object.freeze({
    usageMode: "response",
    responseTypes: Object.freeze(["counter"]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "counter",
    name: "反制",
    category: "tactic",
    targetType: "responseOnly",
    subtypes: Object.freeze(["response", "counter"]),
    description: "响应一张战术牌并取消其效果；面对群伤牌时只取消对自己的效果。",
  }),

  harvest: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "harvest",
    name: "丰收",
    category: "tactic",
    targetType: "none",
    subtypes: Object.freeze(["draw"]),
    description: "摸2张牌。",
    drawCount: 2,
  }),

  duel: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: true,
    selectionFlow: Object.freeze([]),
    definitionId: "duel",
    name: "决斗",
    category: "tactic",
    targetType: "singleEnemy",
    subtypes: Object.freeze(["duel", "attack-discard"]),
    description: "目标先开始，双方轮流打出「突袭」；首先放弃者受到1点伤害。",
    failDamage: 1,
  }),

  mutualBenefit: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: true,
    selectionFlow: Object.freeze(["publicPool"]),
    definitionId: "mutualBenefit",
    name: "互利",
    category: "tactic",
    targetType: "allLiving",
    subtypes: Object.freeze(["public-pool", "draw"]),
    description: "以所有存活角色为规则目标；展示等同存活人数的牌，从你开始按座位顺序每人选择1张。",
    perRecipientDrawCount: 1,
    globalBenefit: true,
  }),

  symbiosis: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: true,
    counterScope: "card",
    ignoresDistance: true,
    selectionFlow: Object.freeze([]),
    definitionId: "symbiosis",
    name: "共生",
    category: "tactic",
    targetType: "allLiving",
    subtypes: Object.freeze(["heal", "global"]),
    description: "令所有存活角色各恢复1点生命。",
    globalBenefit: true,
    healAmount: 1,
  }),

  seal: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "seal",
    name: "封印",
    category: "tactic",
    targetType: "singleUnsealedEnemy",
    subtypes: Object.freeze(["status", "delay", "control"]),
    description: "对一名未处于「封印」状态的敌人使用，使其进入「封印」状态。其下个回合摸牌阶段前判定：为战术牌时「封印」未生效，本回合正常进行；否则「封印」生效，摸牌后跳过出牌阶段。",
    judgmentTriggerCategory: "tactic",
  }),

  lightning: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "lightning",
    name: "闪电",
    category: "tactic",
    targetType: "none",
    subtypes: Object.freeze(["status", "delay"]),
    description: "使用后进入「闪电」状态；下回合摸牌前进行判定。若结果为装备牌，受到3点伤害并移除状态；否则将状态转移给下一名未进入「闪电」状态的角色。",
    judgmentTriggerCategory: "equipment",
    hitDamage: 3,
  }),

  energyDevice: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "energyDevice",
    name: "充能桩",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "energy"]),
    description: "回合开始获得能量时额外获得1点。",
    turnEnergyBonus: 1,
  }),

  recycleDevice: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "recycleDevice",
    name: "回收站",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "draw"]),
    description: "每回合使用战术牌后摸1张，即使该牌被反制；每回合最多触发2次。",
    triggerDrawCount: 1,
    maxUsesPerTurn: 2,
  }),

  defenseDevice: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "defenseDevice",
    name: "雷达",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "judgment", "defense"]),
    description: "对每个格挡需求分别判定：战术牌免除该次格挡需求；基础牌进入手牌后继续结算；装备牌进入弃牌堆并继续结算该次需求。",
  }),

  battleDevice: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "battleDevice",
    name: "军火库",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "attack"]),
    description: "你的「突袭」与「震荡」需要目标一次使用2张「格挡」才能防御；数量不足时不会消耗已有「格挡」。",
    assaultRequiredBlockCount: 2,
  }),

  assaultMagazine: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "assaultMagazine",
    name: "备用弹夹",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "assault-capacity"]),
    description: "你每个出牌阶段主动使用「突袭」的次数上限 +2。",
    attackLimitBonus: 2,
  }),

  telescope: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "telescope",
    name: "望远镜",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "distance", "attack"]),
    description: "你计算与其他角色的距离时-1。",
    outgoingDistanceModifier: -1,
  }),

  barrierDevice: Object.freeze({
    usageMode: "active",
    responseTypes: Object.freeze([]),
    counterable: false,
    counterScope: "card",
    ignoresDistance: false,
    selectionFlow: Object.freeze([]),
    definitionId: "barrierDevice",
    name: "屏障",
    category: "equipment",
    targetType: "self",
    subtypes: Object.freeze(["equipment", "distance", "defense"]),
    description: "其他角色计算与你的距离时+1。",
    incomingDistanceModifier: 1,
  }),

});
